service: storedb

custom:
  stage: ${opt:stage, self:provider.stage}
  accountTable: account-${self:custom.stage}
  reviewTable: review-${self:custom.stage}
  favoriteTable: favorite-${self:custom.stage}
  storeTable: store-${self:custom.stage}
  itemTable: item-${self:custom.stage}
  orderTable: order-${self:custom.stage}
  reservationTable: reservation-${self:custom.stage}
  paymentTable: payment-${self:custom.stage}
  
provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: store_user

resources:
  Resources:
    AccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountTable}
        AttributeDefinitions:
          - AttributeName: accountId
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "accountId-index"
            KeySchema:
              - AttributeName: "accountId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    ReviewTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reviewTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: reviewAt 
            AttributeType: N

          - AttributeName: storeId 
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: reviewAt
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 6
            WriteCapacityUnits: 6
        GlobalSecondaryIndexes:
          - IndexName: "storeId-index"
            KeySchema:
              - AttributeName: "storeId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    FavoriteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.favoriteTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: itemId 
            AttributeType: S

          - AttributeName: storeId 
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: itemId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 6
            WriteCapacityUnits: 6
        GlobalSecondaryIndexes:
          - IndexName: "storeId-index"
            KeySchema:
              - AttributeName: "storeId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    StoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.storeTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: storeId 
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: storeId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.itemTable}
        AttributeDefinitions:
          - AttributeName: storeId 
            AttributeType: S
  
          - AttributeName: itemId 
            AttributeType: S
        KeySchema:
          - AttributeName: storeId
            KeyType: HASH
          - AttributeName: itemId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.orderTable}
        AttributeDefinitions:
          - AttributeName: orderId 
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
         
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    ReservationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reservationTable}
        AttributeDefinitions:
          - AttributeName: id 
            AttributeType: S
  
          - AttributeName: orderId 
            AttributeType: S

          - AttributeName: storeId 
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
       
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "storeId-index"
            KeySchema:
              - AttributeName: "storeId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    PaymentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.paymentTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: createdAt 
            AttributeType: S

        KeySchema:
          - AttributeName: accountId
            KeyType: HASH

          - AttributeName: createdAt
            KeyType: RANGE
       
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
