service: database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locall
  accountTable: account-${self:custom.stage}
  reviewTable: review-${self:custom.stage}
  favoriteTable: favorite-${self:custom.stage}

provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: cloud_user

resources:
  Resources:
    AccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountTable}
        AttributeDefinitions:
          - AttributeName: accountId
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        # GlobalSecondaryIndexes:
        #   -
        #     IndexName: "route_id-index"
        #     KeySchema:
        #       -
        #         AttributeName: "route_id" 
        #         KeyType: "HASH"
        #     Projection:
        #       ProjectionType: "ALL"
        #     ProvisionedThroughput:
        #       ReadCapacityUnits: 5
        #       WriteCapacityUnits: 5
    ReviewTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: reviewAt 
            AttributeType: N
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: reviewAt
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "storeId-index"
            KeySchema:
              - AttributeName: "storeId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    FavoriteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.favoriteTable}
        AttributeDefinitions:
          - AttributeName: accountId 
            AttributeType: S
  
          - AttributeName: itemId 
            AttributeType: S
        KeySchema:
          - AttributeName: accountId
            KeyType: HASH
          - AttributeName: itemId
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: "storeId-index"
            KeySchema:
              - AttributeName: "storeId" 
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5